import { execSync } from 'node:child_process';
import { readFileSync, writeFileSync } from 'node:fs';

import json from '@rollup/plugin-json';
import resolve from '@rollup/plugin-node-resolve';
import typescript from '@rollup/plugin-typescript';

const pkg = JSON.parse(readFileSync('./package.json', 'utf-8'));
let revision = 'unknown';
try {
    revision = execSync('git rev-parse --short HEAD').toString().trim();
} catch (e) { /* keep 'unknown' */ }

writeFileSync('src/lib/version.ts',
`// Auto-generated by rollup.config.mjs. Do not edit.
/**
 * The splat-transform version (semver MAJOR.MINOR.PATCH).
 */
export const version = '${pkg.version}';

/**
 * The splat-transform revision (short Git hash of HEAD at build time).
 */
export const revision = '${revision}';
`);

// Library build - ESM (platform agnostic)
const esm = {
    input: 'src/lib/index.ts',
    output: {
        dir: 'dist',
        format: 'esm',
        sourcemap: true,
        entryFileNames: 'index.mjs'
    },
    external: ['playcanvas'],
    plugins: [
        typescript({
            tsconfig: './tsconfig.json',
            declaration: true,
            declarationDir: 'dist'
        }),
        resolve(),
        json()
    ],
    cache: false
};

// Library build - CommonJS (for non-module apps)
const cjs = {
    input: 'src/lib/index.ts',
    output: {
        dir: 'dist',
        format: 'cjs',
        sourcemap: true,
        entryFileNames: 'index.cjs',
        exports: 'named'
    },
    external: ['playcanvas'],
    plugins: [
        typescript({
            tsconfig: './tsconfig.json',
            declaration: false,
            declarationDir: undefined
        }),
        resolve(),
        json()
    ],
    cache: false
};

// CLI build - Node.js specific
const cli = {
    input: 'src/cli/index.ts',
    output: {
        dir: 'dist',
        format: 'esm',
        sourcemap: true,
        entryFileNames: 'cli.mjs'
    },
    external: ['webgpu'],
    plugins: [
        typescript({
            tsconfig: './tsconfig.json',
            declaration: false,
            declarationDir: undefined
        }),
        resolve(),
        json()
    ],
    cache: false
};

export default [esm, cjs, cli];
