import { execSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';

import pkg from '../package.json' with { type: 'json' };

const revision = () => {
    try {
        return execSync('git rev-parse --short HEAD').toString().trim();
    } catch (e) {
        return 'unknown';
    }
};

const versionTxt =
`// Auto-generated by scripts/gen-version.mjs. Do not edit.
export const version = '${pkg.version}';
export const revision = '${revision()}';
`;

writeFileSync('src/lib/version.ts', versionTxt);
